services:
  kafka-0:
    image: bitnamilegacy/kafka:3.4
    ports:
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server=localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - kafka_0_data:/bitnami/kafka

  kafka-1:
    image: bitnamilegacy/kafka:3.4
    ports:
      - "9095:9095"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://127.0.0.1:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_1_data:/bitnami/kafka

  kafka-2:
    image: bitnamilegacy/kafka:3.4
    ports:
      - "9096:9096"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092,EXTERNAL://127.0.0.1:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_2_data:/bitnami/kafka

  kafka-init:
    image: bitnamilegacy/kafka:3.4
    healthcheck:
      test: [ "CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-0:9092 --list | grep my-topic" ]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      kafka-0:
        condition: service_healthy
    entrypoint: [ "" ]
    command: >
      /bin/bash -c "sleep 10 && 
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists 
      --bootstrap-server kafka-0:9092 
      --partitions 1 
      --replication-factor 2
      --topic messages &&
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists 
      --bootstrap-server kafka-0:9092 
      --partitions 1 
      --replication-factor 2
      --topic blocked-users && 
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists 
      --bootstrap-server kafka-0:9092 
      --partitions 1 
      --replication-factor 2
      --topic filtered-messages &&
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists 
      --bootstrap-server kafka-0:9092 
      --partitions 1 
      --replication-factor 2
      --topic banned-words &&
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists 
      --bootstrap-server kafka-0:9092 
      --partitions 1 
      --replication-factor 2
      --topic blocked-users-group &&
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists 
      --bootstrap-server kafka-0:9092 
      --partitions 1 
      --replication-factor 2
      --topic banned-words-group &&
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists 
      --bootstrap-server kafka-0:9092 
      --partitions 1 
      --replication-factor 2
      --topic blocked-users-group-table &&
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists 
      --bootstrap-server kafka-0:9092 
      --partitions 1 
      --replication-factor 2
      --topic banned-words-group-table"

  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-0:9092,kafka-1:9092,kafka-2:9092
      - KAFKA_CLUSTERS_0_NAME=kraft

  go-app:
    build:
      context: ..
      dockerfile: ./practice2/Dockerfile
    depends_on:
      kafka-init:
        condition: service_completed_successfully

volumes:
  kafka_0_data:
  kafka_1_data:
  kafka_2_data: